### PR TITLE
CA file support for OIDC auth

### PR DESCRIPTION
**Pull request by Didr**
The current OIDC auth flow (#2157) doesn't use `caCertFile` from the config.
This PR copies the result from `getCaTrustCerts` (https://github.com/arkime/arkime/blob/main/viewer/config.js#L199) into the OIDC auth flow and if defined, will use the provided CA to override the default CAs (Mozilla) used in nodejs.

Relevant section from the OIDC library: https://github.com/panva/node-openid-client/blob/main/docs/README.md#customizing-http-requests
Default behavior of "ca" option: https://nodejs.org/api/tls.html#tlscreatesecurecontextoptions

**Did you run `npm run lint` from the viewer or parliament directory (whichever you are making changes to) and correct any errors**
Yes.

**Did you Ensure that all tests still pass by navigating to the `tests` directory and running `./tests.pl --viewer`**
Sadly, I couldn't get this to work. I've manually tested without any auth and with the OIDC auth. I've not tested the header auth.

## License
I confirm that this contribution is made under an Apache 2.0 license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Comment by Didr** [comment]
I realize now that this'll break things if someone is using separate CAs for their OIDC and elastic/opensearch setup.

**Comment by awick** [comment]
This seems fine, other than this is specific to viewer. Maybe should move this out of viewerUtils into ArkimeUtils?

**Comment by Didr** [comment]
Still need to test cont3xt and WISE. I'll leave a message when that's done.

**Comment by awick** [comment]
thanks!

**Pull request merged**
