### PR TITLE
fix history/cron in demo mode

### PR DESCRIPTION
**Pull request by dhakalananda**
A sinlge PR for #2317 and #2318

### CODE REVIEW

**Comment by dhakalananda** [comment]
The reason this is a security issue is because: A demo website is used by multiple users so having the user's history public is an information leak as it contains requests to all the endpoints and all. Having CRUD access to periodic queries should also be forbidden to avoid creating thousands of cron jobs in the app.

**Comment by awick** [comment]
It is a demo instance and we state that everyone can view everyone's data.

history - I do not think is a security issue, agree we should fix
cron - I do see that as potential DOS issue

Unfortunately this PR has a number of issues, I'll be making a new one, thanks for pointing out these issues

**Comment by dhakalananda** [comment]
I have submitted a report on HackerOne #2051313. Please triage it on the platform as well.

**Comment by awick** [comment]
Ok thanks, I don't have access but the BB folks can reply.

**Pull request closed without merging**
