### PR TITLE
Bruteforce resistant key derivation scheme

### PR DESCRIPTION
**Pull request by ahmed-tabib**
The cookie authentication mechanism uses a weak key derivation scheme from the password. It simply hashes the password with SHA-256. This would allow any user with an auth token to launch an offline bruteforce attack on the password. I tested the attack on my personal laptop and achieved speeds of ~110 MH/s.
The solution is simple, I used the crypto.pbkdf2Sync() function instead of SHA with 1,000,000 iterations. This adds a delay of ~100-250ms on startup, but once the key is generated you wouldn't need to do it again.
Also, I added a block that checks when passstore decryption fails, and tries the old key derivation scheme. This probably isn't the right way, I tried to figure out a way to re-encrypt the passstore but I honestly have no idea where to start.

## License
I confirm that this contribution is made under an Apache 2.0 license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Comment by awick** [comment]
Thanks for the PR. 

Can you describe the attack in a little more detail? Since you mentioned the cookie, that is created by Auth.obj2auth, and I thought the iv would protect from the style you describe.

**Comment by ahmed-tabib** [comment]
Yeah absolutely. The way I tested it I used the hmac, since it uses the same key. The signature is calculated as s = hmac(sha256(password), iv+encrypted_content)). Since Hmac is computationally equivalent to 2 passes of sha-256, this allows us to try many many passwords very quickly, like I stated above, having a message and it's hmac, you can try around 110 million passwords per second. I created my own hashcat module for this. I can share it with you if you'd like to run it yourself.

**Comment by awick** [comment]
Sure would you mind email it to arkime.security@yahooinc.com or DM on slack.

**Comment by ahmed-tabib** [comment]
I sent an email with some instructions on building the plugin and running it.

**Comment by awick** [comment]
Thanks, I'm going to be making the changes over on https://github.com/arkime/arkime/pull/2287/files if you can take a look

**Comment by awick** [comment]
thank you for your help

**Pull request closed without merging**
