### PR TITLE
Systemd service identifiers

### PR DESCRIPTION
**Pull request by vpiserchia**
**The Problem**
Systemd do not report the correct service identified.
By using the keyword "SyslogIdentifier" this is possible 

## License
I confirm that this contribution is made under an Apache 2.0 license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Comment by awick** [comment]
How do I test this?

**Comment by vpiserchia** [comment]
when you install/enable/start the service files then you'll see something like in the journal log:

`
May 29 00:33:42 arkime5 arkimeviewer[420205]: This node will process Periodic Queries (CRON) & Hunts, delayed by 85 seconds
`

instead of

`
May 28 13:36:23 arkime5 node[208362]: WARNING - No cronQueries=true found in /data/arkime/viewer/config.ini, one and only one node MUST have cronQueries=true set for cron/hunts to work
`

**Comment by awick** [comment]
How are you getting the logs into your journal log? I don't see any change in wise.log for example.

**Comment by vpiserchia** [comment]
(with shame) Thank you Andy, I missed to commit the latest code 

In order to use systemd and journald I removed the bash script invocation and fully use the systemd directive `StandardOutput` and `StandardError`.

By commenting out these two lines one can decide to have logs in journald or the normal log files.

**Comment by awick** [comment]
Unfortunately these keywords are not available on RHEL 7, so this will need to wait until we drop support, another month or so. (This is why we didn't use them.)

**Comment by vpiserchia** [comment]
understood, sorry for wasting your time; I didn't realize it

**Comment by vpiserchia** [comment]
Closing since RHEL 7 does not support  used directives

**Comment by awick** [comment]
We should do this in the Arkime 5.3 or 5.4 timeframe

**Pull request closed without merging**
