### PR TITLE
Touilleio feature/kafka v3.0

### PR DESCRIPTION
**Pull request by skytelan3**
**Clearly describe the problem and solution**

**Relevant issue number(s) if applicable**

**Did you run `npm run lint` from the viewer or parliament directory (whichever you are making changes to) and correct any errors**

**Did you Ensure that all tests still pass by navigating to the `tests` directory and running `./tests.pl --viewer`**

## License
I confirm that this contribution is made under an Apache 2.0 license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Comment by skytelan3** [comment]
y

**Comment by awick** [comment]
Did you mean to close this PR?

**Comment by Obsecurus** [comment]
Any reason this one got closed @killerwhile?

**Comment by killerwhile** [comment]
The patch is still valid. What's missing so far is a working TLS setup (openssl libs are conflicting in this PR), and rebase towards v4. But it's still heavily used on my side in PROD.
I'll try to find time to finalize it and get it merged properly.

**Pull request closed without merging**
