### PR TITLE
Integration color counts

### PR DESCRIPTION
**Pull request by TobySalusky**
* add severity counts to indicator result nodes
* hover tooltip displays *clickable* Integrations Buttons per category (green counts, grey counts, red counts)
* counts of zero are not shown, so if all are zero, nothing will appear
* IntegrationBtns minor refactors + severity filter added (for use in color-counter tooltip)

### CODE REVIEW

**Comment by 31453** [comment]
Let's merge in the UI reshuffle branch to dev5. This diff is ugly since it has those changes too.

**Comment by TobySalusky** [comment]
> Let's merge in the UI reshuffle branch to dev5. This diff is ugly since it has those changes too.

agreed 👍

**Comment by TobySalusky** [comment]
closing PR due to git sadness.
see https://github.com/arkime/arkime/pull/2358

**Comment by awick** [comment]
so so sad

**Pull request closed without merging**
